name: Running Tests

on: [push]

permissions:
  checks: write

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      # Install PostgreSQL client
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install --yes --no-install-recommends postgresql-client

      # Create database tables
      - name: Create database tables
        run: |
          psql -h localhost -U postgres -d test -c '
          CREATE TABLE categories (id BIGSERIAL PRIMARY KEY, avatar VARCHAR NOT NULL, title VARCHAR NOT NULL UNIQUE); 
          CREATE TABLE club (id BIGSERIAL PRIMARY KEY, title VARCHAR NOT NULL, description VARCHAR NOT NULL, image_url VARCHAR, category_id INT8 REFERENCES categories(id)); 
          CREATE TABLE child (id BIGSERIAL PRIMARY KEY, first_name VARCHAR NOT NULL, last_name VARCHAR NOT NULL, birth_date DATE);
          CREATE TABLE club_child (club_id INT8 REFERENCES club(id), child_id INT8 REFERENCES child(id));'
        env:
          PGPASSWORD: root

      # Setup Java
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      # Run tests with Maven
      - name: Test with Maven
        run: mvn clean test
        env:
          DB_URL: jdbc:postgresql://localhost:5432/test
          DB_USERNAME: postgres
          DB_PASSWORD: root

      # Generate Jacoco report
      - name: Jacoco report generate
        if: success() || failure()
        run: mvn jacoco:report

      # Publish Test Report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

      # Upload Jacoco Report
      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: jacoco-report
          path: '**/target/site/jacoco/'

      # Use an alternative action for Jacoco report summary
      - name: Jacoco Summary
        uses: scacap/action-surefire-report@v1
        with:
          junit_report_paths: '**/target/surefire-reports/TEST-*.xml'
          jacoco_report_paths: '**/target/site/jacoco/jacoco.xml'
